updatecli/website

content/docs/resources/helm_chart.adoc
This pull request will be merged once https://github.com/updatecli/updatecli/pull/194 is merged and available in the next updatecli version
Signed-off-by: Olivier Vernin <olivier@vernin.me>
=> Add helmchart documentation for target

content/docs/resources/github_release.adoc
Add documentaiton related to this [pull request](https://github.com/updatecli/updatecli/pull/196)
=> Document github release typeVersion

content/docs/scm/git.adoc, content/docs/scm/github.adoc
Document this https://github.com/updatecli/updatecli/pull/221
Signed-off-by: Olivier Vernin <olivier@vernin.me>
=> Document git push --force parameter

.github/workflows/build.yaml
Signed-off-by: Olivier Vernin <olivier@vernin.me>
=> Remove npm run clean from github action

content/docs/resources/shell.adoc
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
=> feat: add resource shell

.gitignore, content/docs/resources/aws_ami.adoc
Documentation for this [PR](https://github.com/updatecli/updatecli/pull/265)
=> Add Aws/AMI documentation

content/docs/resources/file.adoc
This PR documents the changes made to the "file" resource in https://github.com/updatecli/updatecli/pull/313.
It applies the same kind of structure as the "shell resource" (#119 ).
=> feat(file) add new feature + examples for the file plugin page

content/docs/resources/transformer.adoc
=> Add transformer documentation: findSubMatch

.gitignore, package-lock.json
=> chore(npm) upgrade package-lock.json to r(d)ecent NPM version

config/_default/config.toml
This configuration is now required 
=> Allow to run asciidoctor

content/docs/prologue/installation.adoc, updatecli/updatecli.d/installation.yaml
This PR introduces updatecli configuration to automate documentation update
/
=> Suse installation

updatecli/updatecli.d/installation.yaml
=> Update repository to update

config/_default/menus.toml, content/docs/plugins/github_pullrequest.adoc
Some vanity metrics do matter...
Display GitHub stars on front page
Look at preview environment
=> Display GitHub start

config/_default/menus.toml, content/docs/plugins/github_pullrequest.adoc
=> Revert "Display GitHub stars"

.github/workflows/updatecli.yaml
=> Updatecli github action uses the master branch

.github/dependabot.yml
=> Add github action to dependabot

.github/workflows/build.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/updatecli.yaml
=> Revert "chore(deps): Bump actions/checkout from 2 to 3"

assets/code_example/doc/guides/helm-chart/updatecli.output, assets/code_example/doc/guides/helm-chart/updatecli.yaml, content/docs/guides/helm-chart.adoc
Signed-off-by: Olivier Vernin <olivier@vernin.me>
A guide to show how to automate helm chart update using updatecli
A guide to show how to automate helm chart update using updatecli
To test this pull request, look at the netflify preview environment or run the following commands on your machine:
```shell
hugo serve
curl http://localhost:1313/docs/guides/helm-chart/
```
/
- [] record a video
=> Add Helm Chart guide

content/docs/prologue/quick-start.adoc, layouts/shortcodes/asciinema.html
Resize asciinema video and move video section
Preview environment
=> Resize asciinema video and move video section

content/docs/core/transformer.adoc
As per : https://github.com/updatecli/updatecli/pull/551#issuecomment-1058903823
Adding information on findSubMatch.
=> feat: add findSubMatch behavior

content/docs/prologue/installation.adoc, updatecli/updatecli.d/installation.yaml
* Add installation instruction for various distribution
* Improve updatecli configuration to handle every distribution
=> Add installation instruction for various distribution

assets/code_example/docs/plugins/git/updatecli.yaml, content/docs/plugins/git.adoc
Well continuing the work to review and update configuration example
=> Update code example

updatecli/updatecli.d/installation.yaml
=> Fix target id

config/_default/params.toml
=> Update Twitter link

.github/ISSUE_TEMPLATE/bug-report---.md, .github/ISSUE_TEMPLATE/feature-request---.md
=> fix: replace 'hyas' by 'updatecli' in issue templates

content/schema/latest/config.json, updatecli/updatecli.d/jsonschema.yaml
To test this pull request, you can look at the preview environment
=> Fix jsonschema updatecli configuration and publish a first schema version

.github/workflows/updatecli.yaml
=> Bump updatecli action version to 1.31.0

updatecli/updatecli.d/npm.yaml
=> Update updatecli manifest for npm version bump

Gemfile.lock
=> Update bundled with versino to 2.3.7

Gemfile.lock
=> Remove bundle with from Gemfile.lock

netlify.toml
=> Revert "[updatecli] Bump npm to libnpmexec-v4.0.4"

updatecli/updatecli.d/npm.yaml
=> Only retrieve npm version matching semantic versioning

updatecli/scripts/jsonschema.sh
=> Update jsonschema script to use file size

content/docs/plugins/shell.adoc
Right now, using the shell and scm together can be a bit confusing.
This is a just FAQ to provide a bit more context until it's addressed
=> Add FAQ to the shell plugins

layouts/partials/head/head.html
I am curious to see what matomoto
=> Test matoto analytics

layouts/index.headers
=> Add cdn.matomo.cloud

assets/scss/common/_variables.scss
We the recent logo change, I propose to stick to the same color
=> Switch principal color from purple to black

.github/workflows/updatecli.yaml
Update to the latest updatecli Github Action version
```shell
act workflow_dispatch -j updatecli  
```
=> Update updatecli GH workflow to v2

.github/workflows/updatecli.yaml
=> Fix wording

content/docs/plugins/maven.adoc
[Documentation](https://www.updatecli.io/docs/plugins/maven/)
Was not really clear to me that it's possible to provide basic auth credentials in the maven url parameter.
=> Document that maven authentication is supported

updatecli/updatecli.d/hugo.yaml, updatecli/updatecli.d/installation.yaml, updatecli/updatecli.d/jsonschema.yaml, updatecli/updatecli.d/node.yaml, updatecli/updatecli.d/npm.yaml
This pullrequest is the result of `updatecli manifest upgrade --config updatecli/updatecli.d --in-place`
This command updates manifest to be compatible with version 0.28.0
=> Update updatecli manifest

content/docs/plugins/shell.adoc
Fix https://github.com/updatecli/updatecli/issues/749
Explain how to use environment variable from shell resource
=> Add shell environment variable doc

updatecli/scripts/jsonschema.sh, updatecli/updatecli.d/installation.yaml
Content path changed with doks v0.5
=> Fix Updatecli manifest

.github/dependabot.yml
Running dependabot on a daily is a bit noisy
=> Run dependabot on a weekly basis

content/en/docs/core/transformer.adoc
Fix example and syntax to avoid warning after copy-and-pasting the examples or reference doc.
=> Update transformers attributes cases (to lowercase)

assets/code_example/docs/plugins/resources/xml/updatecli.d/default.yaml, content/en/docs/plugins/resource/xml.adoc
Init XML documentation 
```shell
go test
```
=> Init xml doc page

layouts/shortcodes/coreparameters.html, layouts/shortcodes/resourceparameters.html
=> Fix resource parameter generator based on jsonschema

content/en/docs/commands/updatecli.md, content/en/docs/commands/updatecli_apply.md, content/en/docs/commands/updatecli_completion.md, content/en/docs/commands/updatecli_completion_bash.md, content/en/docs/commands/updatecli_completion_fish.md, content/en/docs/commands/updatecli_completion_powershell.md, content/en/docs/commands/updatecli_completion_zsh.md, content/en/docs/commands/updatecli_diff.md, content/en/docs/commands/updatecli_jsonschema.md, content/en/docs/commands/updatecli_manifest.md, content/en/docs/commands/updatecli_manifest_show.md, content/en/docs/commands/updatecli_manifest_upgrade.md, content/en/docs/commands/updatecli_prepare.md, content/en/docs/commands/updatecli_version.md
=> Update commands documentation

assets/code_example/docs/plugins/resources/csv/updatecli.d/default.yaml, content/en/docs/plugins/resource/csv.adoc
=> Add csv documentation

.github/workflows/updatecli.yaml, updatecli/updatecli.d/hugo.yaml, updatecli/updatecli.d/node.yaml, updatecli/updatecli.d/npm.yaml
Fix Manifest that used semver version filter that stop dropping v prefix
=> fix semver trim prefix issue in updatecli manifest

assets/code_example/docs/plugins/autodiscovery/fleet/updatecli.d/default.yaml, assets/code_example/docs/plugins/autodiscovery/helm/updatecli.d/default.yaml, assets/code_example/docs/plugins/autodiscovery/helmfile/updatecli.d/default.yaml, assets/code_example/docs/plugins/autodiscovery/maven/updatecli.d/default.yaml, content/en/contact/index.md, content/en/docs/plugins/autodiscovery/fleet.adoc, content/en/docs/plugins/autodiscovery/helm.adoc, content/en/docs/plugins/autodiscovery/helmfile.adoc, content/en/docs/plugins/autodiscovery/maven.adoc, content/en/docs/plugins/autodiscovery/others.adoc
At least we have the placeholder
=> Init autodiscover documentation

assets/code_example/docs/plugins/autodiscovery/dockercompose/updatecli.d/default.yaml, content/en/docs/plugins/autodiscovery/dockercompose.adoc
Related to https://github.com/updatecli/updatecli/pull/973
Add docker-compose documentation
To test this pull request, you can look at the preview environment deployed on Netlify
=> Add docker-compose autodiscovery documentation

assets/code_example/docs/plugins/resources/npm/updatecli.d/default.yaml, content/en/docs/plugins/resource/npm.adoc
Fix https://github.com/updatecli/updatecli/pull/1009
=> Add NPM resource documentation

assets/code_example/docs/plugins/autodiscovery/dockerfile/updatecli.d/default.yaml, content/en/docs/plugins/autodiscovery/dockerfile.adoc
Add Dockerfile autodiscovery documentation
=> Add Dockerfile autodiscovery documentation

.github/workflows/typos.yaml, README.md, _typos.toml, content/en/contact/index.md, content/en/docs/automate/github_action.adoc, content/en/docs/core/autodiscovery.adoc, content/en/docs/plugins/autodiscovery/dockercompose.adoc, content/en/docs/plugins/autodiscovery/dockerfile.adoc, content/en/docs/plugins/autodiscovery/helm.adoc, content/en/docs/plugins/autodiscovery/others.adoc, content/en/docs/plugins/resource/docker_image.adoc, content/en/docs/plugins/resource/npm.adoc, content/en/docs/plugins/resource/yaml.adoc, content/en/docs/prologue/quick-start.adoc, content/en/privacy-policy/index.md, content/en/support/index.md
Introduce typos GitHub action to detect typos
This pullrequest also introduce some rewording suggested by Vale to make sentences shorter.
Visit preview website
=> Add typos detection and fix existing

content/en/docs/help/contributing.adoc
Improve contribution guide based on feedback from: https://github.com/updatecli/updatecli/pull/1081
=> [enh] Add info about test manifest

content/en/docs/prologue/installation.adoc
I've created an AUR package and added it to the install section.
=> Add aur package

updatecli/updatecli.d/hugo.yaml, updatecli/updatecli.d/installation.yaml, updatecli/updatecli.d/jsonschema.yaml, updatecli/updatecli.d/node.yaml, updatecli/updatecli.d/npm.yaml
=> cleanup Updatecli deprecation warning

config/_default/menus/menus.en.toml
Hoping to make the chat more visible to reduce the number of DM
=> Add chat link to menu bar 

content/en/docs/guides/docker-compose.adoc, content/en/docs/guides/helm-chart.adoc, layouts/shortcodes/ide_jsonschema.html, layouts/shortcodes/updatecli_description.html
=> Use generic shortcode for updatecli guides

content/en/docs/core/configuration.adoc
See https://github.com/updatecli/updatecli/pull/1177
=> feat(core/configuration): add note about sprig template functions

config/_default/menus/menus.en.toml
Add updatemonitor link to menu bar
=> Add updatemonitor link to menu bar

content/en/docs/commands/updatecli.md, content/en/docs/commands/updatecli_apply.md, content/en/docs/commands/updatecli_completion.md, content/en/docs/commands/updatecli_completion_bash.md, content/en/docs/commands/updatecli_completion_fish.md, content/en/docs/commands/updatecli_completion_powershell.md, content/en/docs/commands/updatecli_completion_zsh.md, content/en/docs/commands/updatecli_diff.md, content/en/docs/commands/updatecli_jsonschema.md, content/en/docs/commands/updatecli_manifest.md, content/en/docs/commands/updatecli_manifest_show.md, content/en/docs/commands/updatecli_manifest_upgrade.md, content/en/docs/commands/updatecli_prepare.md, content/en/docs/commands/updatecli_show.md, content/en/docs/commands/updatecli_version.md
=> Update commands docs

assets/code_example/docs/plugins/stash/updatecli.yaml, content/en/docs/plugins/scm/stash.adoc
Docu Website for https://github.com/updatecli/updatecli/pull/1233
=> Add Bitbucket Server (Stash)

netlify.toml
... li/website/netlify.toml"
Made with ❤️️ by updatecli
Fix #XXX
```shell
go test
```
---
<details><summary>Updatecli options</summary>
Most of Updatecli configuration is done via Updatecli manifest.
<ul>
<li>If you close this pullrequest, Updatecli will automatically reopen it, the next time it runs.</li>
<li>If you close this pullrequest, and delete the base branch, Updatecli will automatically recreate it, erasing all previous commits made.</li>
</ul>
</details>
---
Action triggered automatically by [Updatecli](https://www.updatecli.io).
Feel free to report any issues at [github.com/updatecli/updatecli](https://github.com/updatecli/updatecli/issues/).
If you find this tool …
=> [updatecli] Bump npm to 9.6.3

content/en/schema/latest/config.json
<Actions>
<action id="03e6edd06fc60c5fdb9c7258c3f367e662c3dc242b09d8eae739e4d130a8183e">
<h3>[updatecli] Bump jsonschema</h3>
<details id="9bbbc0e7d004cda63882b8f5bdddcd3211caa6526492212a48ca524177b27f1e">
<summary>Update updatecli jsonschema</summary>
</details>
</action>
</Actions>
---
<details><summary>Updatecli options</summary>
Most of Updatecli configuration is done via Updatecli manifest.
<ul>
<li>If you close this pullrequest, Updatecli will automatically reopen it, the next time it runs.</li>
<li>If you close this pullrequest, and delete the base branch, Updatecli will automatically recreate it, erasing all previous commits made.</li>
</ul>
</details>
---
Action triggered automatically by [Updatecli](https://www.updatecli.io).
Feel free to report any issues at …
=> [updatecli] Bump jsonschema

layouts/shortcodes/autodiscoveryparameters.html, layouts/shortcodes/resourceparameters.html
This pullrequest is an attempt to better render parameter description generated from the jsonschema
=> Markdownify resource description

assets/code_example/docs/plugins/resources/hcl/updatecli.d/default.yaml, content/en/docs/plugins/resource/hcl.adoc
Related to https://github.com/updatecli/updatecli/pull/1424
=> docs: add hcl resource plugin page

assets/code_example/docs/plugins/autodiscovery/cargo/updatecli.d/default.yaml, assets/code_example/docs/plugins/resources/cargopackage/updatecli.d/default.yaml, content/en/docs/plugins/autodiscovery/cargo.adoc, content/en/docs/plugins/resource/cargopackage.adoc
Add documentation for cargopackage and flesh out the autodiscovery
=> feat: add cargopackage documentation

netlify.toml
Reverts updatecli/website#1115
=> Revert "[updatecli] Bump npm to 10.0.0"

updatecli/updatecli.d/node.yaml
=> disable node update automerge

content/en/docs/plugins/resource/shell.adoc
herit --> inherit
`npm run start`
=> doc: fix typo in shell resource page

layouts/shortcodes/resourceparameters.html
This pullrequest is a follow up of https://github.com/updatecli/updatecli/pull/1570
=> Update jsonschema shortcode to use additionalProperties

updatecli/updatecli.d/node.yaml
=> Monitor node version 20

.github/workflows/updatecli.yaml, updatecli/updatecli.d/autodiscovery-npm.yaml
Automate npm package update using Updatecli
=> Add npm workflow

assets/code_example/docs/plugins/resources/terraform/file/updatecli.d/default.yaml, assets/code_example/docs/plugins/resources/terraform/lock/updatecli.d/default.yaml, assets/code_example/docs/plugins/resources/terraform/provider/updatecli.d/default.yaml, assets/code_example/docs/plugins/resources/terraform/registry/updatecli.d/default.yaml, content/en/docs/plugins/resource/hcl.adoc, content/en/docs/plugins/resource/terraform/file.adoc, content/en/docs/plugins/resource/terraform/lock.adoc, content/en/docs/plugins/resource/terraform/provider.adoc, content/en/docs/plugins/resource/terraform/registry.adoc
Related: https://github.com/updatecli/updatecli/pull/1576
=> docs: add terraform file and registry

assets/code_example/docs/plugins/resources/docker/image/updatecli.d/default.yaml, assets/code_example/docs/plugins/resources/docker/image/values.yaml, content/en/docs/plugins/resource/docker_image.adoc
Also updated the example to work.
=> docs: update docker image docs with note on arhcitectures

layouts/shortcodes/coreparameters.html
=> fix: correctly fetch core parameter from jsonschema

.github/dependabot.yml
=> Stop using dependabot for npm update

content/en/docs/core/shareandreuse.adoc
Documentation related to https://github.com/updatecli/updatecli/pull/1605
To merge once 0.63.0 is released with that feature
=> Add Share & Reuse documentation

content/en/docs/commands/updatecli.md, content/en/docs/commands/updatecli_apply.md, content/en/docs/commands/updatecli_completion.md, content/en/docs/commands/updatecli_completion_bash.md, content/en/docs/commands/updatecli_completion_fish.md, content/en/docs/commands/updatecli_completion_powershell.md, content/en/docs/commands/updatecli_completion_zsh.md, content/en/docs/commands/updatecli_compose.md, content/en/docs/commands/updatecli_compose_apply.md, content/en/docs/commands/updatecli_compose_diff.md, content/en/docs/commands/updatecli_compose_show.md, content/en/docs/commands/updatecli_diff.md, content/en/docs/commands/updatecli_jsonschema.md, content/en/docs/commands/updatecli_manifest.md, content/en/docs/commands/updatecli_manifest_pull.md, content/en/docs/commands/updatecli_manifest_push.md, content/en/docs/commands/updatecli_manifest_show.md, content/en/docs/commands/updatecli_manifest_upgrade.md, content/en/docs/commands/updatecli_prepare.md, content/en/docs/commands/updatecli_show.md, content/en/docs/commands/updatecli_udash.md, content/en/docs/commands/updatecli_udash_config.md, content/en/docs/commands/updatecli_udash_login.md, content/en/docs/commands/updatecli_udash_logout.md, content/en/docs/commands/updatecli_version.md
=> Update command documentation

content/en/docs/plugins/resource/dockerfile.adoc
Fix #XXX
Use lowercase parameters in the examples for the dockerfile
```shell
go test
```
=> use lowercase for the instruction and value parameters

content/en/docs/prologue/installation.adoc
Extending docs regarding asdf installation process for updatecli
=> docs: update installation docs to include asdf

content/en/docs/core/shareandreuse.adoc, layouts/shortcodes/policymetadataparameters.html
Improve share and reuse documentation
=> feat(policy): improve documentation

update-compose.yaml
=> Automate update-compose.yaml update

update-compose.yaml
Remove duplicated "policies" in policy name
=> Cleanup policy path in update-compose.yaml

.github/workflows/updatecli.yaml
=> fix(updatecli): only trigger updatecli for master branch

assets/code_example/docs/plugins/autodiscovery/helm/updatecli.d/default.yaml
Provide examples for the new ignore dependencies/containers in helm autodiscovery
=> Improve examples docs for helm autodiscovery

content/en/blog/2022/12/what_a_year.adoc, content/en/blog/2023/10/time_to_celebrate.adoc, content/en/blog/2024/02/shareable_policies.md
remove experimental mention when not needed
=> chore: remove experimental when not needed

content/en/docs/plugins/autodiscovery/dockerfile.adoc
=> fix: typo in dockerfile.adoc

content/en/docs/plugins/autodiscovery/dockercompose.adoc
=> fix: typo in dockercompose.adoc

.github/workflows/updatecli.yaml
=> deps: bump Updatecli version in GH workflow

.github/workflows/updatecli.yaml, updatecli/values.d/npm.yaml
=> change one npm dep a a time

.github/workflows/build.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/typos.yaml, .github/workflows/updatecli.yaml
=> add merge_group event to required GH workflows

assets/code_example/docs/plugins/autodiscovery/argocd/updatecli.d/updatecli.yaml, content/en/docs/plugins/autodiscovery/argocd.adoc
[Fix #XXX](https://github.com/updatecli/updatecli/pull/2158)
=> feat: add argocd documentation

content/en/blog/2024/05/welcome_releasepost.md
A blogpost to introduce an experiment for republishing release notes
=> feat: welcome releasepost experiment

content/en/docs/plugins/resource/shell.adoc
=> Small corrections on shell.adoc

content/en/docs/automate/github_action.adoc, content/en/docs/automate/jenkins.adoc, content/en/docs/core/autodiscovery.adoc, content/en/docs/core/compose.adoc, content/en/docs/core/condition.adoc, content/en/docs/core/configuration.adoc, content/en/docs/core/scm.adoc, content/en/docs/core/shareandreuse.adoc, content/en/docs/core/source.adoc, content/en/docs/core/target.adoc, content/en/docs/core/transformer.adoc, content/en/docs/guides/docker-compose.adoc, content/en/docs/guides/helm-chart.adoc, content/en/docs/guides/npm.adoc, content/en/docs/help/contributing.adoc, content/en/docs/help/faq.md, content/en/docs/prologue/installation.adoc, content/en/docs/prologue/introduction.md, content/en/docs/prologue/quick-start.adoc, content/en/support/index.md
I had the occasion to use and learn a bit about updatecli for a small task in Kubewarden.io. I took a couple of hours to do a quick review and touched up the docs a bit. I hope that's all ok. Thanks.
=> Minor docs updates for typos and improving readability

content/en/blog/2023/12/oneless_experimentation_autodiscovery.adoc, content/en/blog/2024/02/shareable_policies.md, content/en/blog/2024/05/welcome_releasepost.md, content/en/docs/core/compose.adoc
=> fix: rename update-compose.yaml to updatecli-compose.yaml

content/en/docs/plugins/resource/toolversions.adoc
=> rename Tool version doc title

assets/code_example/docs/plugins/autodiscovery/prow/updatecli.d/updatecli.yaml, content/en/docs/plugins/autodiscovery/kubernetes.adoc, content/en/docs/plugins/autodiscovery/prow.adoc
Relates to https://github.com/updatecli/updatecli/pull/2567
=> feat: add note about prow being supported by the kubernetes autodiscovery

config/_default/params.toml
=> Update Updatecli alert banner

assets/code_example/docs/plugins/actions/bitbucket_pullrequest/updatecli.yaml, assets/code_example/docs/plugins/scm/bitbucket/updatecli.d/default.yaml, content/en/docs/plugins/actions/bitbucket.adoc, content/en/docs/plugins/scm/bitbucket.adoc
Related to: https://github.com/updatecli/updatecli/pull/2847
=> docs: add bitbucket scm and action docs

assets/code_example/docs/plugins/resources/temurin/updatecli.d/default.yaml, content/en/docs/plugins/resource/temurin.adoc
Documents https://github.com/updatecli/updatecli/pull/3063
=> feat(docs): add temurin condition

content/en/docs/prologue/introduction.md
Added a detailed explanation about what a manifest is and its role in Updatecli
=> Add explanation of manifest and its context in Updatecli

assets/code_example/docs/plugins/resources/http/updatecli.d/default.yaml, assets/code_example/docs/plugins/resources/http/updatecli.d/json.yaml, content/en/docs/plugins/resource/http.adoc
As mentioned on https://github.com/updatecli/updatecli/issues/4024
We are missing this documentation page
=> Init http documentation

content/en/docs/plugins/resource/aws_ami.adoc
Add `gp3` as possibile value in `block-device-mapping.volume-type` filter for aws/ami source
=> Add gp3 for volume-type in aws_ami.adoc

assets/code_example/docs/core/action/updatecli.yaml, content/en/docs/core/action.adoc
=> doc: add action documentation

content/en/docs/core/source.adoc
=> doc: add multiple source howto

updatecli/values.d/releasepost.yaml
Forgot to add this value file in a previous pr
=> fix: add missing updatecli/values.d/releasepost.yaml

assets/code_example/docs/plugins/autodiscovery/githubaction/updatecli.d/default.yaml, assets/code_example/docs/plugins/autodiscovery/precommit/updatecli.d/default.yaml, content/en/docs/plugins/autodiscovery/githubaction.adoc, content/en/docs/plugins/autodiscovery/precommit.adoc
Documentation for precommit and githubaction autodiscovery
=> feat: add doc for ad githubaction and precommit

content/en/docs/core/transformer.adoc
Fix [#XXX](https://github.com/updatecli/updatecli/issues/4869)
=> feat: add quote/unquote transformers

content/en/docs/core/autodiscovery.adoc
Document how to use actions within autodiscovery.
=> Document `actionid` in the autodiscovery section

content/en/code-of-conduct/index.md, content/en/support/index.md
The old support page was very small and outdated
=> refactor: revamp support page

content/en/docs/automate/github_action.adoc
Document GITHUB token requirement
=> chore: document GITHUB_TOKEN requirement
