updatecli/website

content/docs/resources/dockerfile.adoc
https://github.com/updatecli/updatecli/pull/176 introduced a new alternative syntax for the resource `Dockerfile`.
This PR add the documentation for this new syntax.
=> Add documentation for the "simpletextmatcher" Dockerfile syntax

.github/workflows/node.js-ci.yml
to allow access for asciidoctor CLI in CI
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
=> fix: add bundle vendor path to system path 

content/docs/resources/shell.adoc
This PR fixes the "shell plugin resource" page with the following changes:
* Removes mentions of 'suppressSource' (introduced in #140) because it was removed in https://github.com/updatecli/updatecli/pull/321
* Mentions the new `disablesourceinput` introduced in https://github.com/updatecli/updatecli/pull/321
* Updates the conventions and look and feel of the page to maps with #161
=> fix(shell) remove mentions of 'suppressSource' and mentions its replacement + nitpicking

content/docs/resources/dockerfile.adoc
- Source is NOT supported for Dockerfile
- typos
- Document the feature https://github.com/updatecli/updatecli/pull/364
=> Fix dockerfile resource page + document the new ENV text matcher for dockerfile

.github/workflows/updatecli.yaml
Don't wait for dependabot to bump updatecli workflow
```shell
go test
```
=> Bump updatecli workflow version to 1.30.0

layouts/index.headers, layouts/partials/head/head.html, netlify.toml
I recently noticed that most of the traffic is not detected by plausible...
Hide plausible script behind netlify proxy as explained on https://plausible.io/docs/proxy/introduction
To test this pull request, you can look to the preview environment
=> Hide plausible script behind netlify proxy

.github/workflows/updatecli.yaml
I don't want to wait for Dependabot to run
=> Bump updatecli version used in by GA

config/_default/menus/menus.en.toml, config/_default/params.toml, content/en/docs/plugins/pullrequest/github.adoc, content/en/docs/plugins/resource/aws_ami.adoc, content/en/docs/plugins/resource/docker_digest.adoc, content/en/docs/plugins/resource/docker_image.adoc, content/en/docs/plugins/resource/dockerfile.adoc, content/en/docs/plugins/resource/file.adoc, content/en/docs/plugins/resource/gitTag.adoc, content/en/docs/plugins/resource/github_release.adoc, content/en/docs/plugins/resource/helm_chart.adoc, content/en/docs/plugins/resource/jenkins.adoc, content/en/docs/plugins/resource/maven.adoc, content/en/docs/plugins/resource/shell.adoc, content/en/docs/plugins/resource/yaml.adoc, content/en/docs/plugins/scm/git.adoc, content/en/docs/plugins/scm/github.adoc
The number of plugin is growing and it's getting difficult to know where to look after information.
I am reorganizing from 
* plugins 
to 
* plugins
* scm
* resource
* pullrequest (need to be renamed to action)
* autodiscovery (coming in a later pr)
To test this pull request, a preview environment is available to visualize the change
Hugo requires menu entry to uniqu which is annoying as Github appears both in pullrequest and scm. I trick Hugo by introducing empty space in some plugin title
=> Reorganize plugin menu

layouts/partials/head/head.html
This file was accidently removed during the latest doks upgrade
=> Enable back default html headers

assets/code_example/docs/core/configuration/values.yaml
[Documentation](https://www.updatecli.io/docs/core/configuration/#_content)
config file references:
```
token: "{{ .github.token }}"
```
but the values file only contains a single `token` key in the root
=> Fix wrong values file example in core/configuration

content/en/docs/plugins/resource/file.adoc
> WARNING: "sourceID" is deprecated in favor of "sourceid".
=> Update deprecate sourceid syntax in file guide

content/en/docs/plugins/resource/file.adoc
First issue I mentioned here is not actually a schema issue but a docs issue:
https://github.com/updatecli/updatecli/issues/866#issuecomment-1280759762
I copy pasted from the docs, and when I setup the json schema it said this was invalid. After looking around a bit I found that it's expected to be in lowercase, I did think it was weird that replacepattern used a different casing
=> Use matchpattern as-in schema

content/en/docs/plugins/autodiscovery/others.adoc
here : https://www.updatecli.io/docs/plugins/autodiscovery/others/ the link for new issue is wrong.
=> chore:  wrong url in FAQ

content/en/docs/core/configuration.adoc
Just a small fix in the configuration page of the docs to make clear which is values and which is the main manifest.
=> Add brief introduction before each code snippet in configuration docs

layouts/shortcodes/coreparameters.html
At the moment the core `spec` description uses the first description in the json schema.
This confused me for a second when I was looking for something:
* Source
> Spec defines settings used to interact with GitLab release	
* Conditions
> Spec defines a specification for a "dockerfile" resource parsed from an updatecli manifest file
* Target
> Spec defines settings used to interact with Gitea release	
* Scms
> Spec defines settings used to interact with Bitbucket release
Also updates indentation of template to make it a little clearer.
=> fix: update confusing core spec docs and add kind docs

assets/code_example/docs/plugins/resources/json/updatecli.d/jenkins-old-versions.yaml, content/en/docs/plugins/resource/json.adoc
I have added a second example manifest for JSON, after [our discussion](https://matrix.to/#/!TQpOBNqKouILtnYnAd:gitter.im/$jc0ZfxaPe0sCy3AvwiketipLFyO8R3gf86HFVU-cSdM?via=matrix.org&via=gitter.im).
My example may be too verbose. 🤔
=> fix(documentation): Adds a second example for JSON

update-compose.yaml
Disabling this policy until I have a fix for https://github.com/updatecli/updatecli/issues/1830
=> chore: disable policy from update-compose.yaml

update-compose.weekly.yaml, update-compose.yaml, updatecli/values.d/compose.yaml
Follow up of https://github.com/updatecli/website/pull/1321
This pullrequest relies on https://github.com/updatecli/updatecli/pull/1921 to be available in release
=> fix: moving releasepost Updatecli pipeline to a weekly schedule 2/2

content/en/docs/core/transformer.adoc
Minor fixes to captureindex behaviour with `0` as index.
=> Clarify captureindex behavior

assets/code_example/docs/plugins/resources/temurin/updatecli.d/default.yaml, content/en/docs/plugins/resource/temurin.adoc
This PR adds the initial documentation for the `temurin` resource introduced in https://github.com/updatecli/updatecli/pull/2556
=> feat: add initial documentation for temurin-adoptium plugin

assets/code_example/docs/plugins/resources/maven/updatecli.d/default.yaml, content/en/docs/plugins/resource/maven.adoc
`url` has been deprecated in maven plugin, hostname should be provided in repository field.
Added comment to document how to provide basic auth credentials
=> Bump maven docs

content/en/docs/plugins/_versionFilter.adoc
Fix for invalid regex pattern in docs ex. https://www.updatecli.io/docs/plugins/resource/github_release/
If you try to use the previous pattern you will get an error ```yaml: line 14: found unknown escape character```
=> Fix for invalid regex pattern

assets/js/index.js, content/en/docs/core/versionFilter.adoc, content/en/docs/plugins/_versionFilter.adoc, content/en/docs/plugins/resource/gitBranch.adoc, content/en/docs/plugins/resource/gitTag.adoc, content/en/docs/plugins/resource/github_release.adoc
https://github.com/updatecli/updatecli/pull/3347
- adds `regex/semver` to versionFilter page
- adds dedicated version filter page
- filter any pages that do not have title from search
=> docs: add regex/semver to versionFilter

content/en/docs/plugins/_versionFilter.adoc
Document versionfilter of kind "time" and "regex/time"
=> feat: document versionfilter of kind time, regex/time, and lex

assets/code_example/docs/plugins/actions/github_pullrequest/updatecli.yaml, assets/code_example/docs/plugins/autodiscovery/fleet/updatecli.d/default.yaml
Update the example documentation for the [Github Pull Request action example documentation](https://www.updatecli.io/docs/plugins/actions/github/#_example) to reflect the new `kind` value of `github/pullrequest` for that action type.
This new value [is taken from the schema that VSCode consumes.](https://www.updatecli.io/schema/latest/policy/manifest/config.json)
When used, the old value of `github` produces a warning:
```
WARNING: The kind "github" for actions is deprecated in favor of 'github/pullrequest'
```
Searched for `kind: github$` in non-`.adoc` files throughout the repository and updated relevant entries.
Checked both updated pages in the netlify preview:
- [PR action docs](https://deploy-preview-2050--amazing-golick-2d0138.netlify.app/docs/plugins/actions/github/)
- [Fleet …
=> Fix out-of-date `kind` field for GitHub Pull Request code examples

assets/code_example/docs/plugins/autodiscovery/golang/updatecli.d/goonly.yaml, assets/code_example/docs/plugins/autodiscovery/golang/updatecli.d/patchonly.yaml, content/en/docs/plugins/autodiscovery/golang.adoc
As reported on the chat the autodiscovery golang plugin is missing the parameter information
=> fix(autodiscovery: golang parameter table)

content/en/docs/help/docker_hub_rate_limit.md
Adds extra documentation on docker hub rate limit which can cause update cli to "soft fail".
=> docs: add docker hub rate limit information

content/en/docs/core/autodiscovery.adoc
Add some missing documentation about the groupby property for the autodiscovery plugin.
Info was provided via the public room, this pr is to persist it for everyone.
=> adding a small note on groupby pr attribute for the autodiscovery plugin
